[package]
name = "cindy-omp-process-container"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[[bin]]
name = "cindy-omp-process-container"
path = "src/main.rs"

[dependencies]
windows-sys = { version = "0.59", features = [
  "Win32_Foundation",
  "Win32_Security",
  "Win32_Storage_FileSystem",
  "Win32_System_Console",
  "Win32_System_Environment",
  "Win32_System_IO",
  "Win32_System_JobObjects",
  "Win32_System_Pipes",
  "Win32_System_Threading",
] }

[profile.release]
panic = "abort"
lto = true
opt-level = "s"
strip = true
